name: 🕌 Al-Hikmah Academy Issue
description: Report a bug or request a feature for the Quran section
title: "[ISSUE]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🕌 Assalamu Alaikum and Welcome!
        
        Thank you for taking the time to report an issue or suggest an improvement for the Al-Hikmah Academy Quran section. Your feedback helps us serve the Muslim Ummah better.
        
        **بسم الله نبدأ** - In the name of Allah, we begin.

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: What type of issue are you reporting?
      options:
        - Bug Report 🐛
        - Feature Request ✨
        - Translation Issue 🌍
        - Audio Problem 🔊
        - UI/UX Improvement 🎨
        - Performance Issue ⚡
        - Documentation 📚
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and detailed description of the issue or feature request.
      placeholder: Describe what happened or what you would like to see implemented...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce (for bugs)
      description: If this is a bug, please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Select '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser(s) are you using?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: false

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Tablet
        - Mobile Phone
        - Other
    validations:
      required: false

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS Monterey, Ubuntu 20.04, iOS 15, Android 12
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the issue here.
      placeholder: Any additional information that might help us understand the issue...
    validations:
      required: false

  - type: checkboxes
    id: islamic-compliance
    attributes:
      label: Islamic Compliance Check
      description: For content-related issues, please confirm Islamic compliance considerations
      options:
        - label: This issue/request aligns with Islamic principles and values
          required: false
        - label: I have verified the accuracy of any Quranic content mentioned
          required: false
        - label: This request respects the sanctity of the Quran and Islamic teachings
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you agree to follow our code of conduct
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided sufficient information for the maintainers to understand and address this issue
          required: true
        - label: I understand this is a volunteer-driven project and responses may take time
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🤲 Dua for Success
        
        **رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ**
        
        *"Our Lord, accept [this] from us. Indeed You are the Hearing, the Knowing."*
        
        جزاك الله خيراً (May Allah reward you with good) for your contribution to this Islamic educational project!
        
        ---
